name: Create New Release for Clip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Compile Clip
        run: |
          agvtool new-version -all $(git rev-parse HEAD)
          # Follow compilation steps from the Clip README
          # The workspace file should be in the root directory after checkout
          git submodule update --init --recursive
          open Clip.xcworkspace # Open the Xcode workspace
          # Note: The following steps (changing the team and building)
          # would typically be done within Xcode, not in the yml file.
          # Ensure your Xcode project is configured to automatically codesign
          # with your development team for the release configuration.
          xcodebuild clean build -workspace Clip.xcworkspace -scheme Clip -configuration Release -destination 'generic/platform=iOS' CODE_SIGNING_REQUIRED=YES CODE_SIGN_STYLE=Auto
          # Create the upload directory and move the ipa file
          mkdir upload
          find . -name "*.ipa" -print0 | xargs -0 mv -t upload/

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/*.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Clip v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
